Repository dinesh-2047/LoopWar, pull requests merged in 2025-08, with the labels that each got.

#18 Updated ReadMe File
  Readme.md
  Screenshots/Features.png
  Screenshots/Footer.png
  Screenshots/HomePage.png
Labels: GSSoC'25, Easy, Level 1

#27 Adding contact page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Contact.jsx
  frontend/src/components/Navbar.jsx
Labels: GSSoC'25, Level 2

#32 Added counter effects to stats section issue number #19
  frontend/src/components/Counter.jsx
  frontend/src/components/Home.jsx
Labels: GSSoC'25, Level 1

#34 add social connection links
  frontend/src/components/Footer.jsx
Labels: GSSoC'25, Level 1

#41 🔼 Feature Request: Add "Back to Top" Arrow for Easy Navigation #21
  frontend/src/App.jsx
  frontend/src/components/BackToTopButton.jsx
Labels: GSSoC'25, Level 1

#60 enhanced leaderboard added
  frontend/src/pages/Leaderboard.jsx
Labels: GSSoC'25, Level 3

#61 added open source page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Opensource.jsx
Labels: GSSoC'25, Level 2

#69 Added Events page
  frontend/src/App.jsx
  frontend/src/components/Event.jsx
  frontend/src/components/Footer.jsx
Labels: GSSoC'25, Level 3
